name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
    - name: Ensure Jest is Installed
      run: npm install jest --save-dev
    - name: Run tests
      run: chmod +x node_modules/.bin/jest && npx jest

  update-taiga:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update Taiga User Story
        uses: lauacosta/backlogr-action@v0.0.2
        with:
          taiga-username: ${{ secrets.TAIGA_USERNAME }}
          taiga-password: ${{ secrets.TAIGA_PASSWORD }}
          project-name: ${{ secrets.PROJECT_NAME }}

  notify-slack:
      name: Notificar a slack
      runs-on: ubuntu-latest
      needs: build-and-test
      if: always()

      steps:
        - name: Notificar éxito en el Pull Request
          if: success() && github.event_name == 'pull_request'
          run: |
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text": "✅ El PR #${{ github.event.pull_request.number }} fue exitoso.\n*Link:* https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}

        - name: Notificar fallo en el Pull Request
          if: failure() && github.event_name == 'pull_request'
          run: |
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"❌ El PR #${{ github.event.pull_request.number }} falló en los tests o el build.\n*Link:* https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
